### ISSUE TITLE
Bitlocker support

### ISSUE THREAD

**Issue by IsaakGroepT** [mhogomchungu/zuluCrypt#109] opened 2019-02-22 08:05 UTC
Not that I want to support closed Microsoft technologies, but it would still be useful to have this GUI work with Bitlocker encrypted drives, for those who are forced to use Windows for certain occasions and want seamless encryption support.

https://github.com/Aorimn/dislocker

**Comment by mhogomchungu** [comment] 2019-02-22 18:38
Will look into adding support for it.

Thanks for making me aware of the project.

**Comment by mhogomchungu** [comment] 2019-02-23 15:18
Is the project still maintained?, its been two years now since the last commit and it has a whole lot of opened issues.

"fsname" fuse option does not work as expected.
"subtype" fuse option does not work as expected as well.

In the below image, the third and the fourth entries will have to be combined and the link between them is "/home/ink/sss/abc/dislocker-file" path.

I will need a way of getting "/home/ink/sss/bitlocker.vhd" path starting from "/home/ink/sss/abc/dislocker-file".

"/home/ink/sss/abc/dislocker-file" path is an implementation detail and a user is not supposed to see them.

There should be a way of customizing the "dislocker-file" name.

From the disklocker-filed path, i will need a way of knowing its "backing file"

![screenshot_20190223_173911](https://user-images.githubusercontent.com/3496115/53287761-f6af9b00-3791-11e9-94ec-2c4aeda54223.png)

**Comment by IsaakGroepT** [comment] 2019-02-23 18:41
It seems like development has stalled yes but Microsoft for example uses dislocker to support the Azure Data Box in Linux. It worked flawless for me

**Comment by mhogomchungu** [comment] 2019-02-25 09:43
Making progress.

You unlock your volumes using a passphrase or bekfile/fvekfile?

![screenshot_20190225_123849](https://user-images.githubusercontent.com/3496115/53328333-c7686d80-38fa-11e9-98cb-4effcb965bc9.png)
![screenshot_20190225_123943](https://user-images.githubusercontent.com/3496115/53328334-c7686d80-38fa-11e9-88df-5cdcfed3331c.png)

**Comment by IsaakGroepT** [comment] 2019-02-25 20:34
Awesome! :smile: 

Until now I used it with a passphrase.

**Comment by mhogomchungu** [comment] 2019-03-03 07:30
The remaining missing functionality is unlocking of volumes and i proceed because of this[1] bug in dislocker.

[1] https://github.com/Aorimn/dislocker/issues/169

**Comment by mhogomchungu** [comment] 2019-03-17 15:41
It should be possible now to unlock bitlocker volumes using zuluCrypt.

1. Build and install dislocker from here[1]. This is my fork and it works around upstream bug that reads passwords only from a terminal.

2. Build zuluCrypt from git.

Will appreciate if you could test.

The current functionality works works with passwords and bitlocker volumes that are in partitions.

[1] https://github.com/mhogomchungu/dislocker

**Comment by IsaakGroepT** [comment] 2019-03-17 17:10
Thanks for adding the support! Will test it one of next days

**Comment by mhogomchungu** [comment] 2019-03-23 08:04
Closing this one because i dont like opened issues.

Will appreciate a comment if you get around to testing the functionality.

**Closed by mhogomchungu** 2019-03-23 08:04 UTC

**Comment by IsaakGroepT** [comment] 2019-03-30 11:49
Hi Francis

So I managed to test it now. Unfortunately it didn't work.

I built & installed your fork of dislocker and zuluCrypt master. I encrypted my USB drive with Bitlocker in Windows 10 using the **compatible** modus. After that I tried the **new** modus (which uses AES-XTS). Both couldn't be unlocked with the same password.

**Comment by mhogomchungu** [comment] 2019-03-30 12:46
Can you unlock the USB drive with upstream dislocker?

**Comment by IsaakGroepT** [comment] 2019-03-30 14:36
Yes, and successfully mounted (took me a while to figure out how though) and create a map and was able to see it in Windows.

But doing the same with your fork also works. It just doesn't with zuluCrypt. Could it maybe be because my password is `test123!!` and the exclamation marks caused an issue? Because in the terminal bash thought I was trying to run the previous command in the end so I had to backslash them.

Commands I used:
```
sudo dislocker -V /dev/sdf1 -utest123\!\! -- /home/ik/disl/
sudo mount -o loop,rw /home/ik/disl/dislocker-file /home/ik/ooo
```

Note that this is still using the **new** encryption modus of Bitlocker in Windows.

**Comment by mhogomchungu** [comment] 2019-03-30 14:48
Where did you put ```dislocker-fuse``` executable from my fork in your system?

zuluCrypt looks for it in these[1] paths

[1] https://github.com/mhogomchungu/zuluCrypt/blob/ed9f04e367655369920e0858bc7d930017f8cf50/zuluCrypt-cli/lib/bitlocker.c#L184-L188

**Comment by mhogomchungu** [comment] 2019-03-30 15:11
Your password is fine, my test password is ```Abc123 @2```. It is just as complicated as yours because both have a spacial character with my special character being the space character.

zuluCrypt should work with any bitlocker volume supported by dislocker.

**Comment by IsaakGroepT** [comment] 2019-03-30 17:49
> Where did you put `dislocker-fuse` executable from my fork in your system?
> 
> zuluCrypt looks for it in these[1] paths
> 
> [1]
> 
> [zuluCrypt/zuluCrypt-cli/lib/bitlocker.c](https://github.com/mhogomchungu/zuluCrypt/blob/ed9f04e367655369920e0858bc7d930017f8cf50/zuluCrypt-cli/lib/bitlocker.c#L184-L188)
> 
> Lines 184 to 188 in [ed9f04e](/mhogomchungu/zuluCrypt/commit/ed9f04e367655369920e0858bc7d930017f8cf50)
>  const char * exe[] = { "/usr/bin/dislocker-fuse", 
>  		       "/usr/local/bin/dislocker-fuse", 
>  		       "/bin/dislocker-fuse", 
>  		       "/opt/bin/dislocker-fuse", 
>  		       NULL } ;

`which dislocker-fuse`:
/usr/local/bin/dislocker-fuse

**Comment by mhogomchungu** [comment] 2019-03-30 18:18
If you have it at ```/usr/local/bin/dislocker-fuse``` then update zuluCrypt from git and try again. There was a bug that caused zuluCrypt to work only if dislocker was located in```/usr/bin/```

**Comment by IsaakGroepT** [comment] 2019-03-31 08:45
Still doesn't work though.

First time I tried to open the drive zC said that an argument was missing. Second and all next attempts zC kept telling me "There seem to be an open volume associated with given address". I checked the mounts and there was a bitlocker mount created by zC, but no mount point for me to use the drive. There was also nothing added to the zC volume list (of open volumes). I umounted and tried again but zC kept repeating itself, also after I disconnected the drive physically.

**Comment by mhogomchungu** [comment] 2019-03-31 08:56
The "argument was missing" error comes from zuluCrypt failing to find dislocker. Are you sure you are using the latest git version?

The open volume comment is due to an existing folder located at ```/run/media/private/ik/cryptoBitlocker```. You will have to manually delete this folder for the error to go away.

**Comment by IsaakGroepT** [comment] 2019-03-31 09:07
About the second error, you're right. That fixed it. Still getting the first error though. Using your fork of dislocker which is is still located in `/usr/local/bin`

**Comment by mhogomchungu** [comment] 2019-03-31 09:24
Are you sure you are running the latest git version of zuluCrypt?. 

The latest git version should have solved this problem for dislocker-fuse located at "/usr/local/bin".

**Comment by IsaakGroepT** [comment] 2019-03-31 09:29
Yes, but I will do a complete reinstall again to be certain.

But can you tell me how I can remove a compiled version of zC properly? Currently I'm forcing an install of zulucrypt-git from Arch AUR and then remove it to delete all the files from my filesystem. Not sure if it doesn't leave any files from the manually compiled version on the fs though

**Comment by mhogomchungu** [comment] 2019-03-31 09:47
If you have more than one version of zuluCrypt installed, ```whereis zuluCrypt-cli``` will tell you where they are.

Installing over the old one should suffice, update from git again and try to unlock and see if you will get any out, if you can then you are running the latest git version.

Output from the latest git will look something like this

```
[ink@mtz ~]$ zuluCrypt-cli -o -d /dev/loop0 -p Abc123@\ 2ee
Looking for dislocker-fuse at "/usr/bin/dislocker-fuse" :FAILED
Looking for dislocker-fuse at "/usr/sbin/dislocker-fuse" :FAILED
Looking for dislocker-fuse at "/usr/local/bin/dislocker-fuse" :PASSED
ERROR: Volume could not be opened with the presented key
[ink@mtz ~]$ 

```

**Comment by mhogomchungu** [comment] 2019-04-01 08:08
I can reproduce the error you are seeing now.

**Comment by mhogomchungu** [comment] 2019-04-01 11:06
Try now after updating from git, i think i have solved the problem.

**Comment by IsaakGroepT** [comment] 2019-04-01 16:34
Still the same error of the one or more argument(s) etc I'm afraid...

Also with the cli executable. It says that it found `dislocker-fuse` in `/usr/local/bin` though

**Comment by mhogomchungu** [comment] 2019-04-01 16:53
Your volume uses what file system?

If its ntfs, do you have a package that provides ntfs-3g executable installed?

Can you crop the first 100MB of your volume and send it to me through my email address of mhogomchungu@gmail.com

You can get the first 100MB of a volume using dd command after running the following command from root's terminal.

```
dd if=/dev/XYZ of=volume.img bs=1024 count=100000
```

where ```/dev/XYZ``` is the path your usb stick with bitlocker volume.

**Comment by IsaakGroepT** [comment] 2019-04-01 17:04
It's NTFS and it's installed yes. I'm using Antergos, so it's installed by default.

Sending you now...

**Comment by mhogomchungu** [comment] 2019-04-06 07:29
The issue should be solved now.

**Comment by IsaakGroepT** [comment] 2019-04-06 08:42
It works. Thanks!

**Comment by mhogomchungu** [comment] 2019-04-06 09:32
Thanks for confirming that it works.

I opened this[1] report to document an odd behavior i saw while troubleshooting the issue.

[1] https://github.com/Aorimn/dislocker/issues/174

**Comment by IsaakGroepT** [comment] 2019-04-06 14:23
Thanks for all the effort! Even though I didn't expect this kind of commitment you have for your software, undoubtedly you deserve an open source reward for it!

**Comment by mhogomchungu** [comment] 2019-05-02 07:41
zuluCrypt 5.5.0 with this feature is released: https://github.com/mhogomchungu/zuluCrypt/releases/tag/5.5.0

**Comment by aardbol** [comment] 2019-05-02 07:52
Great, you're a champion! Would you like me to order an Azure Data Box to see if your Bitlocker support implementation also opens these drives? Their implementation is a bit different than the built-in Bitlocker feature in Windows, so it could mean that zuluCrypt doesn't have full compatibility yet. 

Unfortunately testing it doesn't guarantee that you can fix it, because the Data Box Disk toolset, which is used to decrypt the drives and open them for storage, is provided as a closed source blob. So it all depends on how far you want to take this. I'll be willing to order and test.

**Comment by mhogomchungu** [comment] 2019-05-04 11:55
I don't think i will be able to fix any problems you will find. I forked dislocker and added only what zuluCrypt needed to communicate with it. 

I don't think i can do more.

**Comment by kamdhenu** [comment] 2019-09-10 06:29
I'm using Ubuntu 19.04, and I'm still getting this issue while unlocking a Bitlocker encrypted 500GB portable hard drive.

Both the GUI and cli version are not working for me.

**Output from zuluMount:**
![zuluMount](https://i.imgur.com/Sby37Fc.png)

**Output from zuluCrypt cli:**
```
user@home-tc:~$ zuluCrypt-cli -o -d /dev/sdb1 -p *******
Looking for dislocker-fuse at "/usr/bin/dislocker-fuse" : PASSED
ERROR: Volume could not be opened with the presented key
```
Output from zuluCrypt-cli --test:
```
WARNING: "loop" kernel module does not appear to be loaded,
tests and opening of encrypted containers in files will fail if the module was not built into the kernel

creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: PASSED

open a plain volume with a keyfile: PASSED
closing a plain volume: PASSED

open a tcrypt volume with a key: PASSED
closing a tcrypt volume: PASSED

open a plain volume using a plugin: PASSED
closing a plain volume: PASSED

open a luks volume with a key: PASSED
closing a luks volume: PASSED

open a luks volume with a keyfile: PASSED
closing a luks volume: PASSED

open a luks volume using a plugin: PASSED
closing a luks volume: PASSED

check key slots in use: 30000000

add a key to a luks volume using a key and a key: PASSED
add key to luks volume using keyfile and keyfile: PASSED
add key to luks volume using passphrase and keyfile: PASSED
add key to luks volume using keyfile and passphrase: PASSED

check key slots in use: 11111000

remove a key from a luks volume using a key: PASSED
remove a key from a luks volume using a keyfile: PASSED
check key slots in use: 01011000

check if there are no opened mappers: PASSED
```

**Comment by mhogomchungu** [comment] 2019-09-10 07:42
1. What version of dislocker are you using?
2. From where did you get it?

The dislocker project is found here[1] and zuluCrypt currently work only with its git version. If you are using version 0.7.1 from your distribution then it will not work.

[1] https://github.com/Aorimn/dislocker

**Comment by kamdhenu** [comment] 2019-09-10 10:50
It worked... Thanks for your support.

**Comment by mhogomchungu** [comment] 2020-01-16 14:19
Version 2.3.0[1] of cryptsetup will support unlocking of bitlocker volumes and zuluCrypt 5.7.1 will default to using it instead of dislocker.

Summary:
1. If installed cryptsetup version < 2.3.0, zuluCrypt will always use dislocker to unlock bitlocker volumes.
2. If installed cryptsetup version >=2.30, zuluCrypt will default to using cryptsetup to unlock bitlocker volumes and those who wish you use dislocker instead should first create a file named "dislocker" and place it in "/etc/zuluCrypt" folder.

[1] https://marc.info/?l=dm-crypt&m=157883032724793&w=2
