### ISSUE TITLE
favourites gone after update from 6.0 to 6.1

### ISSUE THREAD

**Issue by thisisgregm** [mhogomchungu/zuluCrypt#182] opened 2022-05-29 15:40 UTC
As title says - favorites gone after updating from 6.0 to 6.1
OS: Xubuntu
ver 6.0 - deb downloaded and installed on 21.10
ver 6.1 - deb downloaded and installed on 22.04

I wouldn't be able to replicate it and it's probably not a big deal for most users, but reporting just in case if you have a simple solution to avoid it in a future.

Thanks.

**Comment by mhogomchungu** [comment] 2022-05-31 09:27
This is fixed now.

I switched to a different favorites systems in version 6.1 and the idea was to copy favorites from the old system to the new system and then delete favorites from the old system but a bug that was caused by accessing not initialized memory prevented copying to the new system.

I didn't catch it in my testing because printing logs while testing caused the memory to accidentally be properly initialized and things working as expected.

**Closed by mhogomchungu** 2022-05-31 09:27 UTC
