### ISSUE TITLE
ZuluCrypt or cryptsetup not accepting settings - still?

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#154] opened 2021-01-23 00:02 UTC
I currently have Ubuntu 20.04 with cryptsetup 2.2.2

I have created a LUKS2 container aes.xts-plain64.512.sha512
cryptsetup luksDump /test/test returns the Digests section: sha256
Do I misunderstand that the problem persists?

_Originally posted by @git70 in https://github.com/mhogomchungu/zuluCrypt/issues/131#issuecomment-764718742_

**Comment by mhogomchungu** [comment] 2021-01-26 13:35
The problem is fixed in cryptsetup 2.2.2 and the LUKS2 volume created with this version of cryptsetup going forward will have the correct setting.

The issue is not fixed in the latest version of zuluCrypt and the LUKS2 volume created with zuluCrypt with any version of cryptsetup will have the wrong setting.

To be able to create a LUKS2 volume with zuluCrypt and have digest hash of sha512 as set by the user, you will need cryptsetp version >=2.2.2(released a while ago) and zuluCrypt version >=5.7.2(Not released yet)

**Comment by git70** [comment] 2021-01-26 14:20
Thank you Francis! 
Good job as always!

I am now pausing my work and waiting for the new version. When will it be available?

I invite you for a beer as soon as ZC 5.7.2 appears ;)
Enter the BTC address.

**Comment by mhogomchungu** [comment] 2021-01-26 17:00
The bitcoin address to use is: 3Q9Y8GUqPBxTfCAdWQVN1BDMzWSqm63pSd

Version 5.7.2 will officially be released this coming weekend but you can get it now from here[1] and to be specific, download and install the following packages-:
1. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/zulucrypt-gui_5.7.1.1611674806.b616d05b-0_amd64.deb
2. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/zulucrypt-cli_5.7.1.1611674806.b616d05b-0_amd64.deb
3. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/libzulucrypt-dev_5.7.1.1611674806.b616d05b-0_amd64.deb
4. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/libzulucrypt1_5.7.1.1611674806.b616d05b-0_amd64.deb

I do not plan to make any more changes for the new release.
[1] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/

**Comment by mhogomchungu** [comment] 2021-01-29 11:14
Version 6.0.0 of zuluCrypt is out and things should now work as expected with this official release.

About that beer, the BTC address is: 3Q9Y8GUqPBxTfCAdWQVN1BDMzWSqm63pSd

Closing this one since the raised issue is not solved but feel free to comment if there is anything else.

**Closed by mhogomchungu** 2021-01-29 11:14 UTC

**Comment by git70** [comment] 2021-01-29 14:55
Great!
THX!
Beer has already gone 3 days ago.
You kept your promise (new version during the weekend) and I also kept ;)
