### ISSUE TITLE
Get device path from mapper requires elevated priviledges

### ISSUE THREAD

**Issue by icyd** [mhogomchungu/zuluCrypt#106] opened 2018-12-14 22:20 UTC
When running `zuluCrypt-cli -P -d /dev/mapper/zuluCrypt-...` returns 
```
ERROR: A non supported device encountered,device is missing or permission denied
Possible reasons for getting the error are:
1.Device path is invalid.
2.The device has LVM or MDRAID signature
``` 
Nevertheless, if the command is run with `sudo` returns the correct path. Should the user be part of a particular group? There is any way to get the path without elevated priviledges?

**Comment by mhogomchungu** [comment] 2018-12-14 22:36
1. What version of zuluCrypt are you using?
2. Where did you get it from?(compiled from source or installed it from distribution's repository)
3. What distribution are you using?

**Comment by icyd** [comment] 2018-12-15 01:03
ZuluCrypt version 5.4.0, Archlinux with linux-lts 4.14.87-1, compile from [https://aur.archlinux.org/packages/zulucrypt/](Aur repository).

**Comment by mhogomchungu** [comment] 2018-12-15 05:18
I can reproduce the issue.

Will work on a fix sometimes in the middle of the next week.

**Comment by mhogomchungu** [comment] 2018-12-19 08:33
Fixed with this[1] commit. Closing this one since its fixed but would appreciate a confirmation. It would worked too if you were also a member of group "zulucrypt".

[1] https://github.com/mhogomchungu/zuluCrypt/commit/a54ff817da7702870ba5cec03af80a33096751c2

**Closed by mhogomchungu** 2018-12-19 08:33 UTC
