### ISSUE TITLE
luks container does not opens from Favorites

### ISSUE THREAD

**Issue by e-voci** [mhogomchungu/zuluCrypt#28] opened 2016-02-29 09:02 UTC
Hello.
I have several encrypted containers created with truecrypt volume type, and one created with luks volume type. While the tc volumes opens from Favorites, the luks one does not ("Could not open encryption routines").
My system is Debian 4.5~rc4-1~exp1 (2016-02-18) x86_64 GNU/Linux
Zulucrypt is 4.7.7 installed from Debian package.

**Comment by mhogomchungu** [comment] 2016-02-29 10:27
Log in to root's account and then run the following command and post its output:

```
 zuluCrypt-cli --test
```

**Comment by mhogomchungu** [comment] 2016-02-29 16:50
Also post the output of the following commands

```
cat /proc/crypto

cryptsetup luksDump /path/to/the/luks/volume
```

The most likely reason i can think of that cause the problem is that the module that contains encryption algorithm used by your luks volume is not loaded.

**Comment by mhogomchungu** [comment] 2016-02-29 19:59
The problem you are having may also be caused by recent changes in the kernel that were fixed in the just released version 1.7.1 of cryptsetup[1]

Your truecrypt volumes are not affected because zuluCrypt uses tcplay to manage truecrypt volumes and uses cryptsetup to manage luks volumes.

Try to unlock your luks volume through cryptsetup and the problem will probably be there too showing the problem is not with zuluCrypt but with cryptsetup.

[1] https://www.kernel.org/pub/linux/utils/cryptsetup/v1.7/v1.7.1-ReleaseNotes

**Comment by e-voci** [comment] 2016-03-03 14:36
Hello.
Thanks for you prompt response.
Attached are the requested log:
1)  zuluCrypt-cli --test
2) cat /proc/crypto
3) cryptsetup luksDump /path/to/the/luks/volume

I am puzzled by the fact that opening the volume from menu "Open > 
Container in a file" works flawlessly, while attempting from menu 
"Favorites > ..." fails.

"Try to unlock your luks volume through cryptsetup": how?

Regards

**Comment by mhogomchungu** [comment] 2016-03-03 16:06
I do not see your attached logs.

can you send them to my email address at "mhogomchungu at GMail.com"?

zuluCrypt 4.9.0 is out,can you uninstall the version you have from debian and then install the version i am offering[1] and try again to see if the problem is still there?

[1] http://mhogomchungu.github.io/zuluCrypt/

**Comment by mhogomchungu** [comment] 2016-03-30 09:41
I am closing this one with "works for me" as i am unable to reproduce it but feel to continue the discussion if anything comes up,maybe i will finally be able to reproduce the issue.

**Closed by mhogomchungu** 2016-03-30 09:41 UTC
