### ISSUE TITLE
"Failed to Locate or Run yubikey's "ykchalresp" when trying to add yubikey to keyslot on ubuntu 20.04

### ISSUE THREAD

**Issue by GIJack** [mhogomchungu/zuluCrypt#174] opened 2022-02-09 00:46 UTC
What:
I am trying to add a yubikey + password to a keyslot on a freshly created luks partition in a hard disk

I am getting error "Failed To Locate Or Run Yubikey's "ykchalresp" Program", as an error.

I have confirmed that the yubikey software is installed from ubuntu, and this program exists
```
$ which ykchalresp
/usr/bin/ykchalresp
$ ykchalresp -V
1.20.0
```

Software:
Ubuntu 20.04 Desktop
zuluCrypt 6.0.0 compiled binaries from the download page for said distro.
![zulucrypt_error](https://user-images.githubusercontent.com/6799601/153100414-1e265306-59f4-4cd9-916d-066157b411d2.png)

If the file does get added, I get the same issue when trying to open a encrypted volume on a hard disk

**Comment by GIJack** [comment] 2022-02-09 18:15
Additional testing. From running STDOUT/STDERR
```

$ zuluCrypt-gui 
Gtk-Message: 10:08:09.981: Failed to load module "canberra-gtk-module"
Failed to get a responce from ykchalresp
StdOUt:
StdError:Yubikey core error: timeout
```

**Comment by mhogomchungu** [comment] 2022-02-10 13:02
The std error message says what the problem is.

Run "ykchalresp" from the terminal and make sure it works properly first.

**Comment by GIJack** [comment] 2022-02-11 19:32
confirmed, the program does in fact work:

$ ykchalresp "test"
09b5c7f421ff6fbb227a040443afd45d0e0df26f

On further testing, it seems to be able to add a key if I hold down the button to the yubikey before confirming, but they will not be able to unlock the volume

might be an issue with timeouts.

**Comment by mhogomchungu** [comment] 2022-03-28 20:32
The yubikey i have requires i press it for it to send its passphrase.

I am closing this one as a "local issue" since things work as expected if you use your yubikey the expected way.

**Closed by mhogomchungu** 2022-03-28 20:32 UTC
