### ISSUE TITLE
Volume could not be opened with the presented key

### ISSUE THREAD

**Issue by mercertom** [mhogomchungu/zuluCrypt#52] opened 2017-01-05 03:56 UTC
I'm using the correct key.

I've also tried copying the TrueCrypt encrypted file, chowning to myself, read and write permissions, and same error. "Volume could not be opened with the presented key".

**Comment by mercertom** [comment] 2017-01-05 04:05
Well, this is interesting. Totally freshly installed zC GUI, and it won't make an encrypted TrueCrypt file. It just hangs, greys everything on the window on the creation dialogue after I press "Create".

File gets created with that name, but can't open it, and the dialogue never finishes with a success message, nor closes.  I  can't quit zC. Just sits there with "Passphrase quality x%" as the window title, everything grey, nothing can be closed/quit/ended.

**Comment by mhogomchungu** [comment] 2017-01-05 06:00
What version of zuluCrypt are you using and on what system.

Your original post seems to be related to this[1] bug report. In a nutshell,its a misleading error when the file system the volume uses is not installed. This bug was fixed in the latest version of zuluCrypt(5.1.0)

[1] https://github.com/mhogomchungu/zuluCrypt/issues/50

**Comment by mercertom** [comment] 2017-01-05 17:15
It is 4.9 Ubuntu, but they were ext4 file system types, which should be installed. Ubuntu runs on ext4 file sytem. If, for example, I use TrueCrypt, I can create and mount a test ext4 Truecrypted file. I cannot mount any of the zuluCrypt created files.

I was able to open these zC created files in my other user account, but now can't open them from a new account on the same machine.

**Comment by mhogomchungu** [comment] 2017-01-05 18:43
It sounds like permission problems on "~/.zuluCrypt" and "`~/.zuluCrypt-socket" folders and these problems were fixed in zuluCrypt 5.0.2 and the latest version of zuluCrypt is 5.1.0.

Try to delete those folders and see if the problem is still there.

A better solution is to use the latest version of zuluCrypt(5.1.0) since it has fixes for these problems.

Can you uninstall the version you have installed and then install a correct version from a list[1] of packages i provide and try again.

Ask for assistance if you fail to install them.

[1] https://github.com/mhogomchungu/zuluCrypt/releases/tag/5.1.0

**Comment by mercertom** [comment] 2017-01-05 20:32
Deleting those folders changed the error to "Volume could not be opened with the presented key", which seems like a step forward.

Earlier I was already trying to install 5.1.0, but the dependencies are giving me lots of trouble on Ubuntu 16.10.

At the step "cmake -DCMAKE_INSTALL_PREFIX=/usr -DSHARE_MOUNT_PREFIX=default -DUDEVSUPPORT=true -DNOGUI=false -DQT5=true -DHOMEMOUNTPREFIX=false -DREUSEMOUNTPOINT=false -DNOGNOME=false -DINTERNAL_ZULUPLAY=false -DNOKDE=false -DINTERNAL_LXQT_WALLET=false -DUSE_POLKIT=false -DCMAKE_BUILD_TYPE=RELEASE . .."

I get 
 No package 'libsecret-1' found
-- Checking for module 'libcryptsetup'
--   No package 'libcryptsetup' found
-- Checking for module 'blkid'
--   No package 'blkid' found
-- Checking for module 'pwquality'
--   No package 'pwquality' found
However, this is really tough for a newbie to deal with, for example, I have libsecret installed, latest version. 2 different ways I've Googled and tried to install it, and both times it's saying I already have it, and it's the latest version. Pretty stuck here. Can't someone just update the PPA that everyone uses (becauses it's the #1 Google result for "install zulucrypt on ubuntu") http://askubuntu.com/questions/483361/how-to-install-zulucrypt-in-ubuntu

**Comment by mhogomchungu** [comment] 2017-01-06 04:07
Using binary package is a lot more convenient,to binary package to use in your case is named 
```zuluCrypt-5.1.0-ubuntu-16.10-Yakkety_Yak.tar.xz```

Download it,extract it and you will see 3 folders in in,the packages to install are in amd64 folder if you are on a 64 bit system.

When installing package from source,development packages are what are usually required. 

If for example,the build process complains that package ```foo``` is not found,what you are supposed to install is a package called ```foo-dev```,aka the development package of foo. 

In your case,packages you are supposed to install are below:

1. libsecret-1-dev
2. libgcrypt20-dev
3. qtbase5-dev
4. cmake
5. pkg-config
6. libcryptsetup-dev
7. libblkid-dev
8. libdevmapper-dev
9. uuid-dev
10, libudev-dev,
11. chrpath
12. bzip2

**Comment by mercertom** [comment] 2017-01-06 18:45
Took me quite a while to remove the 4.9 and install that binary, but now I can open my TrueCrypt files! 

I'm very confused what happened. Made no sense to me why it failed and now works, but thanks for your support and guidance.

Is it difficult to make/maintain a PPA? If so, I'd hijack that AskUbuntu question thread so newbies like me (probably a large fraction of the Ubuntu userbase) get wise and install the latest version via binary.

**Comment by mhogomchungu** [comment] 2017-01-07 20:48
Binary packages are build by OBS(open suse build service)[1] and its possible to offer them in the same way PPA are offered but i do not advertise them because recent versions of ubuntu and debian complains about usage of SHA1 like in this bug report[2]. I will the link prominently displayed once the issue is resolved.

I am closing this bug report because the original problem is solved. Dont hesitate to respond though if anything else comes up.

[1] https://build.opensuse.org/

[2] https://github.com/owncloud/client/issues/4596

**Closed by mhogomchungu** 2017-01-07 20:48 UTC

**Comment by e-voci** [comment] 2017-04-26 07:37
Hello Francis.
I use the binary packages zuluCrypt-5.1.0-debian-8-Jessie on my Debian 4.9.18-1 (64 bit).
I have 8 volumes, created with TrueCrypt. 7 of them mount properly, the height gives since a while "ERROR: Volume could not be opened with the presented key".

I know the password, and have it confirmed by
(a) truecrack package ($ /usr/local/bin/truecrack -t [volume path] -w wordlist -e aes -v), returning "Found password", and
(b) opening the volume from TrueCrypt (Windows). Volume opens, although the windows version cannot mount it because of the ext filesystem.

I've tried:
- to change volume extension
- to completely de-install and re-install zuluCrypt binaries 5.1.0

The volume properties are: AES 256 bits, block 128 bits, Mode XTS, PKCS HMAC-RIPEMD-160, no embedded backup header

Grateful for your support

**Comment by mhogomchungu** [comment] 2017-04-26 13:30
1. run zuluCrypt test and post your output to establish a baseline. You do that by running ```zuluCrypt-cli --test```
2. try to unlock the volume from the terminal and see if it works,you do this by running ```zuluCrypt-cli -o -d path/to/your/volume```

**Comment by e-voci** [comment] 2017-04-26 14:28
Update: after several tests, it seems that the culprit is the 256 bits keysize.
Creating a new volume with 512 bits key shown no problems.
The concern however remains: why truecrypt can and zulucrypt cannot handle 256b keys?

**Comment by e-voci** [comment] 2017-04-26 14:30
Hello, and thanks for the quick reply.

Here follows the requested outputs:

elio@glam:~$ zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: dummykey
PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: PASSED

open a plain volume with a keyfile: PASSED
closing a plain volume: PASSED

open a tcrypt volume with a key: PASSED
closing a tcrypt volume: PASSED

open a plain volume using a plugin: PASSED
closing a plain volume: PASSED

open a luks volume with a key: PASSED
closing a luks volume: PASSED

open a luks volume with a keyfile: PASSED
closing a luks volume: PASSED

open a luks volume using a plugin: PASSED
closing a luks volume: PASSED

check key slots in use: 30000000

add a key to a luks volume using a key and a key: PASSED
add key to luks volume using keyfile and keyfile: PASSED
add key to luks volume using passphrase and keyfile: PASSED
add key to luks volume using keyfile and passphrase: PASSED

check key slots in use: 11111000

remove a key from a luks volume using a key: PASSED
remove a key from a luks volume using a keyfile: PASSED
check key slots in use: 01011000

check if there are no opened mappers: FAILED
found opened mapper: /dev/mapper/zuluCrypt-1000-NAAN-(omitted)
found opened mapper: /dev/mapper/zuluCrypt-1000-NAAN-(omitted)
found opened mapper: /dev/mapper/zuluCrypt-1000-NAAN-(omitted)
found opened mapper: /dev/mapper/zuluCrypt-1000-NAAN-(omitted)
found opened mapper: /dev/mapper/zuluCrypt-1000-NAAN-(omitted)

elio@glam:~$ zuluCrypt-cli -o -d (omitted)
Enter passphrase:
ERROR: Volume could not be opened with the presented key
elio@glam:~$

Please check my last post.

Thanks for your support

Elio

------------------------------------------------------------------------
/*Elio VOCI*
VOIP Phone +39-0962-1876 557** Fax +39-0962-1870 163
Mobile IT +39-329-2343 564** BE +32-478-110 660
Skype elio.voci** Webhttp://www.linkedin.com/in/eliovoci
/
------------------------------------------------------------------------

**Comment by mhogomchungu** [comment] 2017-04-26 19:01
I think the primary header on your eighth volume is busted and those other tools hides it because they automatically try a back up header and zuluCrypt does not do that

I just added a commit[1] that makes it do that too and this should solve your problem.

You can get binaries with the fix here[2] http://download.opensuse.org/repositories/home:/mhogomchungu/Debian_8.0/amd64/

[1] https://github.com/mhogomchungu/zuluCrypt/commit/7ec6bef6ce22ede66646d876588787407bf8b9c9

[2] http://download.opensuse.org/repositories/home:/mhogomchungu/Debian_8.0/amd64/

**Comment by e-voci** [comment] 2017-04-27 06:46
Thanks.
I've downloaded and installed the new binaries, but the problem persists.
Are you sure that this issue is not related with the keysize 256b?
Is there a way to compare primary and backup headers, to verify if any 
corruption occurred?

Regards/
/

------------------------------------------------------------------------

**Comment by mhogomchungu** [comment] 2017-04-27 07:11
what does 256b mean? is it 256 bits ie 32 bytes or 256 bytes?

If they are bytes then that could be a problem,try to use only 63 bytes of your password and try again.

**Comment by e-voci** [comment] 2017-04-27 07:38
Hello.

In "Volume Properties", one of the entries, the third, is "keysize".
For 7 out 8 of my volumes, this is set to "512 bits".
The volume I cannot open with zuluCrypt has a keysize of "256 bits".

The password of that volume has a 16 characters.

Regards/
/

------------------------------------------------------------------------

**Comment by mhogomchungu** [comment] 2017-04-27 10:00
Can you create another volume that has the same behavior and send it to me?

**Comment by e-voci** [comment] 2017-04-27 10:21
I've tried with the current versions of TrueCrypt and zuluCrypt, and 
both create an AES+RIPEMD volume with keysize 512b.

Most probably my faulty volume was created with an older version of 
TrueCrypt, it dates back to 2003.

I'll see if I can find an old version of TrueCrypt to play with./
/

------------------------------------------------------------------------

**Comment by mercertom** [comment] 2020-04-25 01:26
Something just broke, now getting "Volume could not be opened with the presented key". Gonna try rebooting, as maybe the kernel and other updates have to apply for it to function.

**Comment by mercertom** [comment] 2020-04-25 01:34
That solved it. Just for future visitors to this thread, first thing to try is reboot. If any packages have updates in the waiting, it can somehow break zuluCrypt and give you "Volume could not be opened with the presented key" until you restart.

**Comment by rocketraman** [comment] 2020-06-07 09:05
Ran into this myself and was an orphan device mapper volume. To fix without a reboot:

```
$ sudo dmsetup ls --target crypt
zuluCrypt-0-NAAN-sdg1-4214101330        (253, 11)

$ sudo cryptsetup close zuluCrypt-0-NAAN-sdg1-4214101330
```

**Comment by mhogomchungu** [comment] 2020-06-07 09:50
What version of zuluCrypt are you using?

**Comment by apg036** [comment] 2020-06-07 10:40
I had the same issue after upgrading from Ubuntu 19.10 to 20.04 LTS - the upgrade process replaced my packages from Github with those from Ubuntu.

The solution provided by @rocketraman helped to clean up the stale mappers and `sudo zuluCrypt-cli --test` started to work without issues

BTW what's the proper way to query the version? Neither `-v `not `--version` don't work for me:
```
$ sudo zuluCrypt-cli -v
zuluCrypt-cli: invalid option -- 'v'
run zuluCrypt-cli --help for help
Version  : 5.7.0
Copyright: 2011-2019 Francis Banyikwa,mhogomchungu@gmail.com
License  : GPLv2+
```

**Comment by rocketraman** [comment] 2020-06-07 13:33
I believe it's `-V`. `-h` is helpful.

**Comment by rocketraman** [comment] 2020-06-07 14:18
```
# rpm -q --info zulucrypt
Name        : zulucrypt
Version     : 5.7.0
Release     : 1.fc31
Architecture: x86_64
```
