### ISSUE TITLE
Systray icon not shown

### ISSUE THREAD

**Issue by jleclanche** [mhogomchungu/zuluCrypt#76] opened 2017-10-22 17:07 UTC
On LXQt, the systray icon is not shown for both zulucrypt and zulumount, instead we see a gear icon (the default "missing" icon):
![image](https://user-images.githubusercontent.com/235410/31864358-a3b226a6-b764-11e7-9567-bfa18d9633d1.png)

**Comment by mhogomchungu** [comment] 2017-10-22 17:55
What version of LXQt are you seeing this behavior in and what version of zuluCrypt are you running that shows this behavior.

**Comment by jleclanche** [comment] 2017-10-22 18:01
0.12 and latest. Note that the systray spec was recently replaced and lxqt no longer supports the legacy x11 systray spec, but I forgot the relevant names.

**Comment by mhogomchungu** [comment] 2017-10-22 18:17
zuluCrypt uses QSystemTrayIcon[1] only and icons shows up fine in plasma5 and gnome as shipped by ubuntu 17.10.

Do other applications that use QSystemTrayIcon Qt API show their icons normally?

![screenshot_20171022_211533](https://user-images.githubusercontent.com/3496115/31864901-51597f94-b76e-11e7-8a03-add49cb92a6a.png)

![screenshot_20171022_211630](https://user-images.githubusercontent.com/3496115/31864903-55916ca2-b76e-11e7-8a5d-28a3eb4b7316.png)




[1] http://doc.qt.io/qt-5/qsystemtrayicon.html

**Comment by jleclanche** [comment] 2017-10-22 18:33
Curious. It could be a problem with detecting the icon itself then. Can you point me to where in the code you set up the systray?

**Comment by mhogomchungu** [comment] 2017-10-22 18:49
I though so too. The code that sets the icon is here[1].

You can set different icons through "menu->options->select icons"

[1] https://github.com/mhogomchungu/zuluCrypt/blob/a610dd4b2c3916e0f67de6ed594c0a3779f1ccae/zuluCrypt-gui/utility.cpp#L2139

**Comment by jleclanche** [comment] 2017-10-22 19:01
Hm, only error I see is `void DBusMenuExporterPrivate::fillLayoutItem(DBusMenuLayoutItem*, QMenu*, int, int, const QStringList&): No id for action`

It looks like this only happens when Options -> Select Icons is set to `zuluCrypt`. The other ones work fine.

**Comment by mhogomchungu** [comment] 2017-10-22 19:05
So it doesnt work with default icons and the problem is probably with my use of "QIcon::fromTheme()", maybe my icons are too small for this API?

**Comment by mhogomchungu** [comment] 2017-10-24 14:34
Both icons show up ok in lxqt 0.11.1 in ubuntu 17.10

![Uploading Screenshot_20171024_173220.png…]()

**Comment by mhogomchungu** [comment] 2017-10-24 18:52
I am closing this one as i think the problem is local, maybe you need to log out and log back in to force the desktop to update its list of icons it knows about.

**Closed by mhogomchungu** 2017-10-24 18:52 UTC
