### ISSUE TITLE
Polkit issue, zuluCrypt doesn't start

### ISSUE THREAD

**Issue by hasufell** [mhogomchungu/zuluCrypt#100] opened 2018-06-03 16:41 UTC
I tried to start `zuluCrypt-gui` via dmenu, not  console, and the dialog https://user-images.githubusercontent.com/3496115/34454627-345a5b28-ed80-11e7-9632-b724a9807efb.png appeared, similar to https://github.com/mhogomchungu/zuluCrypt/issues/85. Trying via command line it asks for a password, but it still fails with "AUTHENTICATION FAILED" and the above dialog.

version is 5.4.0

**Comment by mhogomchungu** [comment] 2018-06-03 22:40
What desktop environment are you using?

Reboot your system and try again to see if the problem is still there.

I have noticed the same thing happening after updating KDE libraries but without first logging out and then loggin in or rebooting.

**Comment by hasufell** [comment] 2018-06-03 23:43
> What desktop environment are you using?

None. I use i3 with some minor xfce functionality and ConsoleKit2.

> Reboot your system and try again to see if the problem is still there.

I'm not on windows :roll_eyes: 

For now,  I just disabled polkit support.

**Comment by mhogomchungu** [comment] 2018-06-04 05:12
Polkit must be broken on your system and logging out and logging back in should have been enough if the problem was due to mismatches in polkit related libraries because some of them were updated and not properly picked up.

zuluCrypt by default does not use polkit support and it has to be compiled with a specific switch to use it.

The only binary distributions i know that uses zuluCrypt with polkit support are debian, ubuntu and fedora.

Closing this one since you went with a work around. Feel free to reopen it if you found out that polkit works correctly other places but broken only in zuluCrypt.

**Closed by mhogomchungu** 2018-06-04 05:12 UTC

**Comment by hasufell** [comment] 2018-06-04 11:06
> Polkit must be broken on your system

Why do you assume that?

**Comment by mhogomchungu** [comment] 2018-06-04 11:33
because zuluCrypt with polkit support would have worked otherwise :-)

you can do a simple test, open the terminal and then run the following command and see if you will get a GUI polkit prompt.

```
pkexec ls
```
