### ISSUE TITLE
device mapper throwing alignment warnings

### ISSUE THREAD

**Issue by pspot2** [mhogomchungu/zuluCrypt#25] opened 2015-12-29 13:40 UTC
Hi,

first of all, excellent job! zuluCrypt is a perfect software for an easy way of working with VeraCrypt volumes.

I've been using it for a while already for accessing a VeraCrypt/NTFS partition on a 1TB disk. Now I also decided to convert another partition - this time on a different 6TB HDD - to VeraCrypt/NTFS. When opening this 5.3TB VeraCrypt/NTFS partition with zuluCrypt, I'm getting alignment warnings from device mapper. Details below.

The smaller partition that works perfectly is 630GB on a MBR-partitioned drive:

                                             Disk: /dev/sda
                        Size: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
                                   Label: dos, identifier: 0xdf108350

    Device         Boot              Start           End       Sectors      Size    Id Type   
  /dev/sda1      *                  2048     629147647     629145600      300G    83 Linux             
    /dev/sda2                    629147648    1953519615    1324371968    631.5G     7 HPFS/NTFS/exFAT
    Free space                  1953519616    1953525167          5552      2.7M

The encrypted volume was created and NTFS-formatted by VeraCrypt 1.13 under Windows 7. When opening it using zuluCrypt, everything is fine: 

Dec 29 12:13:39 nuc kernel: device-mapper: uevent: version 1.0.3
Dec 29 12:13:39 nuc kernel: device-mapper: ioctl: 4.30.0-ioctl (2014-12-22) initialised: dm-devel@redhat.com
Dec 29 12:13:39 nuc kernel: sha256_ssse3: Using AVX2 optimized SHA-256 implementation
Dec 29 12:13:43 nuc kernel: fuse init (API version 7.23)
Dec 29 12:13:43 nuc ntfs-3g[3333]: Version 2014.2.15 external FUSE 29
Dec 29 12:13:43 nuc ntfs-3g[3333]: Mounted /dev/mapper/zuluCrypt-1001-NAAN-sda2-4071757814 (Read-Write, label "NTFS_DATA", NTFS 3.1)
Dec 29 12:13:43 nuc ntfs-3g[3333]: Cmdline options: rw,nodev,nosuid,relatime,dmask=0000,umask=0000,uid=1001,gid=1001,fmask=0111
Dec 29 12:13:43 nuc ntfs-3g[3333]: Mount options: rw,nodev,nosuid,allow_other,nonempty,relatime,default_permissions,fsname=/dev/mapper/zuluCrypt-1001-NAAN-sda2-4071757814,blkdev,blksize=4096
Dec 29 12:13:43 nuc ntfs-3g[3333]: Global ownership and permissions enforced, configuration type 7

The bigger partition is 5.3TB on a GPT-partitioned drive:

GPT fdisk (gdisk) version 0.8.10

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/sdc: 11721045168 sectors, 5.5 TiB
Logical sector size: 512 bytes
Disk identifier (GUID): 13D8DC95-4747-4B4A-8FFC-A31296739A2C
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 11721045134
Partitions will be aligned on 2048-sector boundaries
Total free space is 2014 sectors (1007.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048          206847   100.0 MiB   8300  Boot
   2          206848       105064447   50.0 GiB    8300  Root
   3       105064448       314779647   100.0 GiB   8300  Backup
   4       314779648     11721045134   5.3 TiB     8300  Data

The encrypted volume was created and NTFS-formatted by VeraCrypt 1.16 under Windows 7. When opening it using zuluCrypt, the device mapper throws alignment errors:

Dec 29 12:19:23 nuc kernel: device-mapper: table: 254:1: adding target device sdc4 caused an alignment inconsistency: physical_block_size=4096, logical_block_size=512, alignment_offset=0, start=0
Dec 29 12:19:23 nuc kernel: device-mapper: table: 254:1: adding target device sdc4 caused an alignment inconsistency: physical_block_size=4096, logical_block_size=512, alignment_offset=0, start=0
Dec 29 12:19:27 nuc kernel: device-mapper: table: 254:1: adding target device sdc4 caused an alignment inconsistency: physical_block_size=4096, logical_block_size=512, alignment_offset=0, start=131072
Dec 29 12:19:27 nuc kernel: device-mapper: table: 254:1: adding target device sdc4 caused an alignment inconsistency: physical_block_size=4096, logical_block_size=512, alignment_offset=0, start=131072
Dec 29 12:19:28 nuc ntfs-3g[3488]: Version 2014.2.15 external FUSE 29
Dec 29 12:19:28 nuc ntfs-3g[3488]: Mounted /dev/mapper/zuluCrypt-1001-NAAN-sdc4-1790378342 (Read-Write, label "NTFS_BIGDATA", NTFS 3.1)
Dec 29 12:19:28 nuc ntfs-3g[3488]: Cmdline options: rw,nodev,nosuid,relatime,dmask=0000,umask=0000,uid=1001,gid=1001,fmask=0111
Dec 29 12:19:28 nuc ntfs-3g[3488]: Mount options: rw,nodev,nosuid,allow_other,nonempty,relatime,default_permissions,fsname=/dev/mapper/zuluCrypt-1001-NAAN-sdc4-1790378342,blkdev,blksize=4096
Dec 29 12:19:28 nuc ntfs-3g[3488]: Global ownership and permissions enforced, configuration type 7

As you can see from the partition tables, both partitions are aligned properly (2048) at partitioning time. Apart from the size and the partitioning scheme (MBR vs GPT), the only difference between these partitions is the partition type which is 7 (NTFS) for the smaller one and 83 (Linux) for the bigger one. I don't know whether this makes some difference because there is a VeraCrypt container around the actual filesystems.

Thanks

**Comment by mhogomchungu** [comment] 2016-01-07 17:40
This is a strange bug report,i did not get an email notification for it and for days ago,i kept getting "page not found" error when i try to access it from github's traffic page since it showed up there.

My apologies for a late reply,i am replying now because i just got access to the it.

Your problem seems to be related to this one[1] i have been following in cryptsetup mailing list,are you the one that opened it?

[1] http://www.saout.de/pipermail/dm-crypt/2016-January/004921.html

**Comment by mhogomchungu** [comment] 2016-01-07 18:01
Do you also get these warnings when you unlock the volume using VeraCrypt in linux?

**Comment by mhogomchungu** [comment] 2016-01-09 18:39
I am closing this bug report since what is reported here is beyond what zuluCrypt can do.

There is a discussion about your issue and you can follow it at the link i gave above,a different "view" of the discussion can be seen from this link[1]. I hope you will participate in that discussion and answer the questions they ask so that a better understanding of what is going on with your hard drive can be achieved.

The summary of the discussion so far is that those are just warnings and you can ignore them and the worst that can happen with them is degraded performance.

[1] http://www.saout.de/pipermail/dm-crypt/2016-January/thread.html#4921

**Closed by mhogomchungu** 2016-01-09 18:39 UTC

**Comment by pspot2** [comment] 2016-01-10 03:13
Based on the latest infos in that thread, are you sure that zuluCrypt does not insert its own padding somehow? It seems strange that the issue is present on a 6TB drive, but is not present on a 1TB one. I also tried creating a VeraCrypt volume with zuluCrypt (and not with VeraCrypt program) with the same result.

If you are absolutely sure, I'll open a bug with VeraCrypt directly.

**Comment by mhogomchungu** [comment] 2016-01-10 05:17
```
Based on the latest infos in that thread, are you sure that zuluCrypt does not insert its own padding somehow?
```

Opening the volume with VeraCrypt and see if those same warnings are generated may answer the above question.

**Comment by mhogomchungu** [comment] 2016-01-10 08:21
FYI,

The infrastructure in the linux kernel that deals with block device encryption is called "dm-crypt".

Both zuluCrypt(its backend actually) and veracrypt uses this infrastructure for user data encryption/decryption and you will most likely get the same warnings even when you unlock the volume using veracrypt because those warnings comes from this infrastructure that is used by both projects.

Run "dmsetup table" command after you have unlocked the volume with VeraCrypt and you will see the same output you saw when you unlocked the volume using zuluCrypt.

You most likely will get the same warnings if you create a linear mapper or any other kind of a mapper using dm infrastructure.The problem is most likely with how a hard drive of  like yours are handled or with how partitions were created on that drive.

Are you sure windows does not give more or less similar warnings about the drive?

**Comment by pspot2** [comment] 2016-01-10 20:23
Windows is completely silent.

Anyway, the issue seems to be resolved in the dm-crypt thread. Thanks for assistance.
