### ISSUE TITLE
problem with the user name

### ISSUE THREAD

**Issue by tuxnvape** [mhogomchungu/zuluCrypt#90] opened 2018-01-13 14:51 UTC
Hi, recently, I have used zuluCrypt, logged in as a user in which there is the character '-' in the user name. And so we have an error permission when I have entered the key to open the container.

**Comment by mhogomchungu** [comment] 2018-01-24 10:10
I can not reproduce this.

What version of zuluCrypt are you using and where did you get it from?

**Comment by tuxnvape** [comment] 2018-01-24 12:46
The version is 5.4.0-1. I get it from Arch Linux User Repository using manjaro.
Here is the link : https://aur.archlinux.org/packages/zulucrypt/

**Comment by mhogomchungu** [comment] 2018-01-24 12:50
what is the output of the following commad:

```
 zuluCrypt-cli --test
```

**Comment by tuxnvape** [comment] 2018-01-24 12:59
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: PASSED

open a plain volume with a keyfile: PASSED
closing a plain volume: PASSED

open a tcrypt volume with a key: PASSED
closing a tcrypt volume: PASSED

open a plain volume using a plugin: PASSED
closing a plain volume: PASSED

open a luks volume with a key: PASSED
closing a luks volume: PASSED

open a luks volume with a keyfile: PASSED
closing a luks volume: PASSED

open a luks volume using a plugin: PASSED
closing a luks volume: PASSED

check key slots in use: 30000000

add a key to a luks volume using a key and a key: PASSED
add key to luks volume using keyfile and keyfile: PASSED
add key to luks volume using passphrase and keyfile: PASSED
add key to luks volume using keyfile and passphrase: PASSED

check key slots in use: 11111000

remove a key from a luks volume using a key: PASSED
remove a key from a luks volume using a keyfile: PASSED
check key slots in use: 01011000

check if there are no opened mappers: PASSED

**Comment by mhogomchungu** [comment] 2018-01-24 14:53
The CLI components works fine, still getting the permission denied error with GUI component?

**Comment by mhogomchungu** [comment] 2018-11-07 09:09
Closing this one since i cant reproduce it.

**Closed by mhogomchungu** 2018-11-07 09:09 UTC
