### ISSUE TITLE
zuluCrypt does not see encrypted partitions

### ISSUE THREAD

**Issue by harley-peter** [mhogomchungu/zuluCrypt#107] opened 2019-02-10 11:35 UTC
I encrypted 4 partitions on 3 hard disks and it works till now but today I cannot open the partitions. If I start zuluCrypt-gui and try to open a partition in the dialog box is nothing listed, it is empty. How can I open the encrypted partitions?

If I try to start zuluCrypt-cli I get the following error:
zuluCrypt-cli: symbol lookup error: /usr/lib/x86_64-linux-gnu/libzuluCrypt.so.1.2.0: undefined symbol: gcry_cipher_close

Can someone help?

**Comment by mhogomchungu** [comment] 2019-02-10 12:20
What distribution are you using and how did you get zuluCrypt?

zuluCrypt project depends on a library called "libgcrypt" and it looks like your system is now using an updated and incompatible version of the library.

The solution here is to recompile zuluCrypt to force it to start using the updated library.

**Comment by harley-peter** [comment] 2019-02-10 12:51
I use siduction, based on debian.
I have installed the following libraries:

ii  android-libcrypto-utils                          1:8.1.0+r23-4
ii  libcrypt2:amd64                                  1:4.1.1-1  
ii  libcrypto++6                                     5.6.4-8 
ii  libcryptsetup1                                   2:1.3.0-3.1
ii  libcryptsetup12:amd64                            2:2.1.0-1    

and yes, the problem occured after a system upgrade yesterday.

How can I recompile zuluCrypt and zuluMount? I am not a developer and so I don't know something about this.

**Comment by mhogomchungu** [comment] 2019-02-10 12:55
If you installed zuluCrypt from your distribution repository, then the solution is to tell them the problem and ask them to rebuild zuluCrypt.

**Comment by mhogomchungu** [comment] 2019-02-12 17:10
Closing this one because the problem is a packaging issue and your distribution is the one to solve it by recompiling zuluCrypt.

**Closed by mhogomchungu** 2019-02-12 17:10 UTC
