### ISSUE TITLE
Feedback about article mention the tool

### ISSUE THREAD

**Issue by wikimatze** [mhogomchungu/zuluCrypt#26] opened 2016-01-03 17:19 UTC
Hi there, I couldn't find another way to contact you, but I've extended my article about device encryption under <http://staging.wikimatze.de/encrypt-your-external-device>. Did I mention the tool in the right way? I found it very handy to work with the gui instead of the command-line.

If there is another way how I can advertise the tool, please let me know.

Bests from Berlin,

Matthias

**Comment by mhogomchungu** [comment] 2016-01-03 20:11
most people contact me through "mhogomchungu@gmail.com" email address and this explains why the bug report list is not very long.

Are you sure you have the ppa path correct? This one[1] has "hda-me" while your link has "had-me"

About mentioning the tool in the right way,i do not know how the ubuntu packages you linked to were created so i cant comment on them,but the ubuntu packages together with debian packages i am offering on the project's main page were created in a way that allows volumes to be unlocked from user's account and your zuluMount example is a mistake since the normal user that run the command will not have access to the mount point because it exists in root's private space.

The experience i am aiming for and that is found in packages i am offering allows both zuluCrypt and zuluMount CLI and GUI to unlock volumes from normal user accounts.

Creation of volumes in hard drives still require elevated privileges ONLY if the device is found to be a system device. What "system device" mean is explained in the project's FAQ page[2]

Thanks for checking out zuluCrypt and finding it worthy of mentioning it and documenting it.

Thanks for the offer and will get back to you when i see an opportunity for you to advertize the tool.

I am closing this bug report since its not a bug report and there is nothing to solve but feel free to continue commenting if anything comes up.

[1] https://launchpad.net/~hda-me

[2] https://github.com/mhogomchungu/zuluCrypt/wiki/Frequently-Asked-Questions

**Closed by mhogomchungu** 2016-01-03 20:11 UTC
