### ISSUE TITLE
Error while trying to create an Encrypted Container In A File

### ISSUE THREAD

**Issue by JakeSFR** [mhogomchungu/zuluCrypt#105] opened 2018-11-24 20:25 UTC
I've built the latest zuluCrypt in Fatdog64-800a and having a problem while attempting to create a new Encrypted Container In A File.

With the default settings it yields:

> Could not open cryptographic back end to generate random data

and aborts.

It's ok if I check "Do Not Write Random Data To Container...", though.

I also tried it in VBox with pclinuxos64-MATE-2018.06 + zuluCrypt-nokde-5.4.0 pkg from repo and it happens there, too.

Anyway, I'm not familiar with C++ at all, but at least managed to narrow it down a little by inserting some debug printfs to the sources and it turns out, that in **::Task::future< int >& utility::clearVolume** function (or whatever it is?) in zuluCrypt-gui/utility.cpp at line 911 the file descriptor gets -1 value and the volumeMapperPath does not correspond to the actual filename in /dev/mapper/.

```
}else{
	auto volumeMapperPath = utility::mapperPath( volume ) ;

	utility::fileHandle f( _openVolume( volumeMapperPath ),_closeFunction( volumePath ) ) ;

	int fd = f.handle() ;

	printf(">>> %d\n", fd);
	printf(">>> %s\n", volumeMapperPath.toStdString().c_str() );

	if( fd == -1 ){

		return 1 ;
		

```
Result:
			
```
>>> -1
>>> /dev/mapper/zuluCrypt-0-NAAN-zzz-3236590735
```

Actual filename:

```
# ls -l /dev/mapper/z*
lrwxrwxrwx 1 root root 7 Nov 24 20:48 /dev/mapper/zuluCrypt-0-NAAN-zzz-2069730152 -> ../dm-4
# 
```

As you can see the suffixes differ.
Btw, the path to the container file was /root/zzz.

Well, that's where my abilities end, unfortunately, but I hope you can pick up the ball and run with it...

**Comment by mhogomchungu** [comment] 2018-11-25 04:57
Add ```perror ( ">>>);``` line to also print a reason for why it failed.

I suspect you are getting "permission denied error" and not what the error you expect of "no such file or directory"

**Comment by JakeSFR** [comment] 2018-11-25 14:10
I hardcoded that suffix that appears in /dev/mapper/ for '/root/zzz' container here, in **QString utility::mapperPath( const QString& r,const QString& component )**:

```
if( component.isEmpty() ){

	//path += "-NAAN-" + rpath.split( "/" ).last() + utility::hashPath( rpath.toLatin1() ) ;
	path += "-NAAN-" + rpath.split( "/" ).last() + "-2069730152" ;
}else{
	path += component + rpath.split( "/" ).last() + utility::hashPath( rpath.toLatin1() ) ;
}
```

and now it works...

**Comment by JakeSFR** [comment] 2018-11-25 19:55
Ok, I think I know where the difference between suffixes comes from.
It's AUFS related.

I noticed this in **zuluCryptLoopDeviceAddress_2()**, in _zuluCrypt-cli/lib/create_loop_device.c_:

`string_t st = String_1( "/sys/block/",device + 5,"/loop/backing_file",NULL ) ;`

and it gave me a hint, so I checked how the path to a container looks like in backing_file:

```
# cat /sys/block/loop6/backing_file 
/aufs/pup_rw/root/zzz
# 
```

And indeed - if, instead of **/root/zzz**, I use **/aufs/pup_rw/root/zzz** path in the GUI, it works and both suffixes are the same.

So, looks like the problem is that **zuluCryptCreateMapperName()** in _create_mapper_name.c_ and **QString utility::mapperPath()** in _utility.cpp_ are simply using different paths for calculating the hash.

If I hardcode the "/aufs/pup_rw" prefix in ::mapperPath():

```
if( component.isEmpty() ){

	//path += "-NAAN-" + rpath.split( "/" ).last() + utility::hashPath( rpath.toLatin1() ) ;
	path += "-NAAN-" + rpath.split( "/" ).last() + utility::hashPath( ("/aufs/pup_rw" + rpath).toLatin1() ) ;
}else{
	path += component + rpath.split( "/" ).last() + utility::hashPath( rpath.toLatin1() ) ;
}
```

it works as well...

**Comment by mhogomchungu** [comment] 2018-11-26 18:40
You are around the fourth person who reported this bug and for the life of me, i could not figure out what was the problem and i simply couldn't reproduce it on my local systems.

I fail to understand why the kernel would later on return "/aufs/pup_rw/root/zzz" when given earlier "/root/zzz" as a loop device path.

So, whats the solution here? I can't create a loop device in zuluCrypt-gui to try to figure out what device path the kernel will give back when asked because using loop devices requires elevated privileges. 

Play guess work and prepend "/aufs/pup_rw/" path when it operation failed with "no file or directory" error? Doing guess work on a device that is about to be wiped out with random data is not a good idea.

Having zuluCrypt-gui call zuluCrypt-cli with a path and ask it to give the path back and use the return path? This will pollute and already very polluted zuluCrypt-cli command line argument list but seems to be the safest alternative.

**Comment by JakeSFR** [comment] 2018-11-26 19:59
> You are around the fourth person who reported this bug and for the life of me, i could not figure out what was the problem and i simply couldn't reproduce it on my local systems.
> 
> I fail to understand why the kernel would later on return "/aufs/pup_rw/root/zzz" when given earlier "/root/zzz" as a loop device path.

I only know why it's "pup_rw" specifically, but also have no idea why the kernel returns it in the first place, instead of the direct path that was provided earlier.
Btw, here are some details on how AUFS is set up in Fatdog: http://distro.ibiblio.org/fatdog/web/faqs/filesystem.html

There's more to it, though - I just found that this behaviour has yet another consequence (not related to AUFS this time).
If you'll attempt to create a container file in a directory that is a symlink to another dir, e.g.:

`/mnt/sda5/B/zzz`

where B is a symlink to A, you'll get this in backing_file:

```
# cat /sys/block/loop6/loop/backing_file 
/mnt/sda5/A/zzz
# 
```

and of course "Could not open cryptographic back end...".


> So, whats the solution here? I can't create a loop device in zuluCrypt-gui to try to figure out what device path the kernel will give back when asked because using loop devices requires elevated privileges.

Hmm, is there no other way to get the path in zC-cli, without the need of using backing_file?


> Play guess work and prepend "/aufs/pup_rw/" path when it operation failed with "no file or directory" error? Doing guess work on a device that is about to be wiped out with random data is not a good idea.

Yeah, and it wouldn't work well anyway.
In Fatdog it could be e.g. _/aufs/{pup_rw,pup_save,devsave,pup_multi}_, depending on the mode and some other factors.
Similarily, in Puppy Linux and its derivatives it's not _/aufs/_, but _/initrd/_.
In PCLOS it's _/union/_ and so on...


> Having zuluCrypt-gui call zuluCrypt-cli with a path and ask it to give the path back and use the return path? This will pollute and already very polluted zuluCrypt-cli command line argument list but seems to be the safest alternative.

Well, if there's no other way...

**Comment by mhogomchungu** [comment] 2018-11-27 13:34
>> Hmm, is there no other way to get the path in zC-cli, without the need of using backing_file?

I do not know it.

Well, the fundamental problem is how to create an image file with cryptographically sound random data. The current solution is doing the following:

1. Create a sparse file of requested size.
2. Attach a loop device to the sparse file.
3. Create a plain dm-crypt device with a 64 byte random data and then attach the loop device to it.
4. Write zeros on the dm-crypt device path.
5. Close the dm-crypt device.
6. Detach the loop device.

In the above steps, zuluCrypt-gui did step 1 and 4 while zuluCrypt-cli did step 2,3,5 and 6.

An alternative is for zuluCrypt-gui to create an image file and write cryptographically random data itself. The source of random data could be "/dev/urandom", libgcrypt's "gcry_randomize()" API among other sources.

I initially went with the first mentioned way because it was faster in my local tests.

Will add the second way as a fall back method when the first way fail.

**Comment by mhogomchungu** [comment] 2018-11-29 12:08
This commit[1] solves the issue. The new default behavior is for zuluCrypt-gui to create the image file and fill it up with random data obtained from "/dev/urandom". The old way is still around and it can be switched by flipping a config option named "UseDmCryptForRandomData" located at "~/.config/zuluCrypt/zuluCrypt.conf".

I am closing this one for one but feel free to reopen or comment is anything comes up.

Thank you very, very, very much for your effort in this bug report.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/3a099c46bb446c9bfee9fa023ead62ee30c3f4c4

**Closed by mhogomchungu** 2018-11-29 12:08 UTC

**Comment by JakeSFR** [comment] 2018-11-29 13:45
Great, thank you for fixing it!
I can confirm it works down here, too.

Cheers!
