### ISSUE TITLE
zuluCrypt and polKit

### ISSUE THREAD

**Issue by pck1980** [mhogomchungu/zuluCrypt#85] opened 2017-12-30 11:40 UTC
Hi,
I'm having an issue with zuluCrypt on Solus OS. I reported it there, but the maintainer suggested it might be an upstream issue, so I'm reporting it here, too.
When I start zuluCrypt-gui or zuluMount-gui on Solus, a polkit password prompt appears, for the program wants to be executed with root permissions.
However, if one chooses to cancel that prompt and restarts zuluCrypt afterwards, no further prompt appears, but instead, the program launches and shows nothing but an empty, white window. In addition, there's a warning saying: "There seem to be another instance running,exiting this one".
Furthermore, a process /usr/bin/zuluPolkit is running with root permissions.

I don't have any other distro installed right now, so I can't tell if the problem is exclusive to Solus or not.

**Comment by mhogomchungu** [comment] 2017-12-30 11:51
What version of zuluCrypt are you using?

The first time around when you enter correct root's password,the program works as expected?

**Comment by pck1980** [comment] 2017-12-30 12:07
I'm currently on a different computer, so I can't look directly, but it seems as Solus is using version 5.4.0-3 of zuluCrypt: https://dev.solus-project.com/source/zuluCrypt/repository/master/

If the correct password is entered, everything works as expected.

**Comment by mhogomchungu** [comment] 2017-12-30 13:46
When you cancel the polkit dialog prompt,do you get below dialog window?

```
Furthermore, a process /usr/bin/zuluPolkit is running with root permissions.
```
This suggests a serious problem with polkit because it launches this application with root's privileges without a correct root's password.

Where is the report you filed with your distribution?

What desktop environment are you using?

![screenshot_20171230_164130](https://user-images.githubusercontent.com/3496115/34454627-345a5b28-ed80-11e7-9632-b724a9807efb.png)

**Comment by pck1980** [comment] 2017-12-30 14:00
No, I don't get this error dialog.
The original bug report can be found here: https://dev.solus-project.com/T5410

I'm using Budgie as desktop environment.

**Comment by mhogomchungu** [comment] 2017-12-30 14:28
This is the first time i am hearing "Budgie" desktop environment. Will install it within a day or two to check it out and investigate the issue but i am confident the problem is with the DE handling of polkit prompt

**Comment by pck1980** [comment] 2017-12-30 17:35
I just retried and found that I was wrong about the /usr/bin/zuluPolkit process.
If I read the output of 'ps' correctly, the process is /usr/bin/pkexec, and /usr/bin/zuluPolkit is the first parameter it was called with.
pkexec is setuid root, so this process can run with root privileges even without entering the correct password.

**Comment by pck1980** [comment] 2017-12-30 17:39
One more thing: When one closes the blank, white window, said pkexe-process also dies.
On the next attempt to launch zuluCrypt, the password prompt is correctly shown.

**Comment by mhogomchungu** [comment] 2017-12-30 18:48
I installed the desktop on ubuntu and i can reproduce the problem.

1. Open the terminal and run ```pkexec ls``` and then click ```cancel``` on the generated polkit prompt and observe the command hanging.

2. Press ```Ctrl+C``` to terminate the hanged process and then repeat the command at step 1 entering a correct password on the polkit prompt and observe it returns immediately.

3. In conclusion, the problem is on ```pkexec``` hanging when a user cancel the polkit prompt making the problem outside of zuluCrypt.

**Comment by mhogomchungu** [comment] 2017-12-30 23:15
I am closing this one since the problem is on the desktop's polkit prompt and not on zuluCrypt. I have filed a bug with the desktop as seen above and the issue in zuluCrypt will be gone when its fixed there.

**Closed by mhogomchungu** 2017-12-30 23:15 UTC
