### ISSUE TITLE
BUILD_INSTRUCTIONS: zuluCrypt-test

### ISSUE THREAD

**Issue by Piraty** [mhogomchungu/zuluCrypt#53] opened 2017-01-08 16:51 UTC
Hi,

I'm building your software on linux.

I was following your build instructions, which helped me very well, but i get some errors on runtime and investigated the instructions again, which state:
```
*****************************************************************************************************

After you have it installed,run "zuluCrypt-test" to make sure everything is working as expected.
```
But the mentioned `zuluCrypt-test` command is not present, not in build folder nor in installed folders.

PS:
Before i file a probably unnessesary issue: what are runtime dependencies (maybe this solves my error)? on mounting a veracrypt-file i keep getting the error 
> unrecognized ERROR with status number 255 encountered
This error occured on this setup:
- zuluCrypt 5.1.0, built from source with provided built instructions
- VoidLinux
- the file is named: a!e.hc (it is openable with veracrypt, which i built from source too)

**Comment by mhogomchungu** [comment] 2017-01-08 19:14
That documentation is out of date and needs to be updated,the command to run is 
```zuluCrypt-cli --test```

What error did you get?

Run time dependencies are the following folder paths:
1. $HOME/.zuluCrypt
2. $HOME/.zuluCrypt-socket
3. /run/media/private,/run/media/public/

All those folders are zuluCrypt internal folders and it should be able to correctly create them. The first two holds zuluCrypt's configuration files and the last ones are used to host mount points.

**Comment by mhogomchungu** [comment] 2017-01-08 19:24
That is an error i did not anticipate,

What version of zuluCrypt did you use to try to unlock your VeraCrypt volume?

What operating system are you using?

Does the full path to your VeraCrypt contains atleast one accented character?

**Comment by Piraty** [comment] 2017-01-09 18:59
(i updated my initial issue)
This error occured on this setup:
- zuluCrypt 5.1.0, built from source with your provided built instructions
- VoidLinux, glibc
- the file is named: a!e.hc (it is openable with veracrypt, which i built from source too)

Indeed did the path contain an exclamation mark, but using a clean path results in the same error message.

**Comment by mhogomchungu** [comment] 2017-01-10 03:59
I cant think of a reason why its not working for you.

Can you give me a download link of VoidLinux you are using? I would like to do local tests to see whats going on.

Also,post the output of the following command: ```zuluCrypt-cli --test```

**Comment by mhogomchungu** [comment] 2017-01-10 04:03
Also,can you create with VeraCrypt a 10MB image file that has the same problem with zuluCrypt and send it to me using "mhogomchungu@gmail.com" email address,

**Comment by Piraty** [comment] 2017-01-10 15:14
Hi, here is the output of the command.
Previously i asked for "Runtime dependencies", what i meant was: packages that are required during runtime, but not necessarily at build time, so they may be absent on my system.
```
$ zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: FAILED
```

**Comment by mhogomchungu** [comment] 2017-01-10 15:22
Login to root's account and run these commands and post the output of the last one,the last command will ask you for a password,enter anything and press enter.

```
truncate -s 10m test.img
cryptsetup --debug luksFormat test.img

```

**Comment by Piraty** [comment] 2017-01-10 16:04
cryptsetup reports:`command succesful`. The file can also not be opened in zuluCrypt.
I tried creating a file in zuluCrypt, which gave me this: `Could not open cryptoraphic back end to generate random data`. Therefore i guess it somehow cannot find the runtime dependencies

**Comment by mhogomchungu** [comment] 2017-01-10 18:24
```
# Crypto backend (LibreSSL 2.4.4) initialized in cryptsetup library version 1.7.3.
```
Never seen that one before,is this done distro wide? why is wrong with libgcrypt that causes you guys to move away from it? Some sort of a conflict between librecrypt and libgcrypt could be the cause of the problem.

Just saw this[1]. Those zuluplay sources are the same and you can use either one, and i created the second one on the list as an independent project because some distributions do not like bundling and they wanted zuluplay as an external dependency they can manage independently of zuluCrypt. 

zuluCrypt does not auto update,the checking for update functionality just reports installed version of zuluCrypt(found locally) and the latest version of zuluCrypt(found by accessing the internet) and the user manually actives this check through "zuluCrypt-gui->menu->help->check for updates". 

I think you should revert that patch as it breaks zuluCrypt for no good reason,zuluCrypt does not and will not automatically access the internet without a user asking it to.

[1] https://github.com/Piraty/void-packages/blob/zulucrypt/srcpkgs/zulucrypt/template

**Comment by Piraty** [comment] 2017-01-10 19:29
Thanks for your reply,

the error message is present without the "disable-update-notification" patch too.
I use this patch because in my point this feature is useles for software that is provided by a package manager.
Thanks for noticing the gcrypt-thing. this is intentional as well as distro-wide. LibreSSL instead of openSSL. If I have time i will look into it.

is there another way to gather debugdata from your application?

**Comment by mhogomchungu** [comment] 2017-01-11 13:30
I cant seem to be able to reproduce the problem, from here[1], i downloaded 
```void-live-x86_64-20160420-cinnamon.iso``` and installed it and fully updated it and then i build zuluCrypt 5.1.0 manually(didnt use the source build system) and all tests passed here.

Screenshot below shows the end part of ```zuluCrypt-cli --test" in void linux.

![screenshot_20170111_161818](https://cloud.githubusercontent.com/assets/3496115/21850283/eb33ef02-d81a-11e6-8be8-9eb07bd409c9.png)


[1]https://repo.voidlinux.eu/live/current/

**Comment by mhogomchungu** [comment] 2017-01-11 13:39
No,there is no other way to gather debug information and there should have been a printed reason of why it failed in your case. 

Is your system fully updated? did you do the testing on an installed system or on a system that was running as a live cd?

**Comment by Piraty** [comment] 2017-01-11 17:45
Thank you for testing it in void linux yourself!!

I am using an up to date system on real hardware, but the issue seems to lie on my side, i will investigate and report back.

Thanks so far, good feedback!

**Comment by Piraty** [comment] 2017-01-11 18:39
silly me. it was privilege related.
`sudo zulucrypt-gui` gives no direct mount error afterall and does not fail with the previuously mentioned "error 255". after accepting the passphrase, for some reason git-cola is opened and then firefox with the path to the mounted file. but my file manager (thunar) does not show the mounted device as such.
terminal keeps showing something like this:
```
thunar-volman: device type  "(null)" is not supported
thunar-volman: unknown block device type "disk".
thunar-volman: unknown block device type "disk".

```

zulucrypt seems unable to ask for sudo/su rights, like for example veracrypt or octoxbps can [1](https://github.com/aarnt/octoxbps/search?q=gksu).

**Comment by mhogomchungu** [comment] 2017-01-11 19:14
zuluCrypt does not need sudo/su/pkexec because zuluCrypt-cli and zuluMount-cli binaries are suid-root. zuluCrypt should just work after you install it without any further action on your part. In worked fine on my void linux test system without changing anything.

Uninstall the version you have and then build it "manually" without using void linux infrastructure and see if you still have the problem. Or try to install it on a clean void linux system running in virtualbox and try again.

Thuner will not show the mounted volume and i explained the reason here: https://github.com/mhogomchungu/zuluCrypt/wiki/Frequently-Asked-Questions#10-zulucrypt-volumes-do-not-show-up-in-nautilus-left-panelwhose-bug-is-it

**Comment by mhogomchungu** [comment] 2017-01-11 19:24
zuluCrypt-cli and zuluMount-cli binaries should have permissions of "4755". The problem is therefore on your build system not setting proper permissions.

**Comment by mhogomchungu** [comment] 2017-01-13 09:24
I am closing this one since the problem is a "broken install" due to a local problem of how you build and install zuluCrypt and not on upstream zuluCrypt.

I am closing it but feel free to comment if anything else comes up.

**Closed by mhogomchungu** 2017-01-13 09:24 UTC
