### ISSUE TITLE
gui not work good with linux mint sarah.

### ISSUE THREAD

**Issue by ZerooCool** [mhogomchungu/zuluCrypt#51] opened 2016-12-14 01:51 UTC
gui not work good with linux mint sarah.

When i create a FILE, and, clic CREATE, i see options selected and grey screen, and, can"t close this windows.

If you have a good idea ?

**Comment by mhogomchungu** [comment] 2016-12-14 05:46
What version of zuluCrypt are you using?

The latest version is 5.0.2 and it fixed this issue.

Uninstall the version you are using and then install this version obtained from here[1] and try again. The name of the package to download and install is "zuluCrypt-5.0.2-ubuntu-16.04-Xenial_Xerus.tar.xz"

[1] https://mhogomchungu.github.io/zuluCrypt/

**Comment by ZerooCool** [comment] 2016-12-18 19:23
Zulucrypt is interesting and I will test it again soon.

I used the version in the Linux Mint Sarah software packages.
Can not give the exact version.

I have not yet reinstalled zulucrypt to test because i now use ccrypt.

I've read that encrypting a file on an unencrypted hard drive, with an unencrypted swap, is not it useful? I do not know if it's worth encrypting, if the hard drive is not encrypted and the swap is not encrypted. This already allows the flaw?

**Comment by mhogomchungu** [comment] 2016-12-19 18:21
A user of linux mint "sarah" contacted me with the same problem and they gave me access to their computer through teamviewer and i was able to trouble shoot the problem and solved it so i know the problem is fixed in your distribution because i fixed while testing in that particular distribution.

Different programs leak all sorts of information in all sort of places in your computer and hence its hard to predict what "secrets" the application you are using to view your decrypted files leaves behind and this is the source of a problem in managing sensitive files in an unecrypted system.

A little security is better than no security and i think you should encrypt your stuff and try to be careful of what programs you use to access your sensitive files and try to find out what sort of infrortaion and where they keep about files they are processing.

I am closing this one because i think the problem is fixed with the latest version.

**Closed by mhogomchungu** 2016-12-19 18:21 UTC

**Comment by ZerooCool** [comment] 2016-12-21 18:04
I retested. Ok. Well functional now. Thank you !
