### ISSUE TITLE
[Feature request] Yubikey as a challenge:response 2FA

### ISSUE THREAD

**Issue by bungabunga** [mhogomchungu/zuluCrypt#118] opened 2019-05-18 12:47 UTC
Would you consider adding an option to have Yubikey (models 4, 5 and Neo) as a challenge:response 2FA with LUKS containers?

Pros:
- having a device with secure element as a 2FA is more secure than keyfiles because keyfiles can be stolen (even from USB key) if the computer gets a trojan.
- Yubikey [already works](https://askubuntu.com/questions/599825/yubikey-two-factor-authentication-full-disk-encryption-via-luks) as a challenge:response 2FA with LUKS with linux full-disk encryption so I guess [implementing](https://github.com/cornelinux/yubikey-luks) it in zuluCrypt (full-disk + container encryption) shouldn't be very hard.
- although Yubikey firmware is closed source computer software for Yubikey is open source.
- Yubikeys are widely used globally, some even consider Yubikey a security standard.

I guess you'd say: but I don't have a Yubikey! Well, I made a similar feature request in the past for Keepass4Android and the developer said the same. Then I made a ticket in Yubico customer support asking them for a free Yubikey for the developer. They responded in just few hours and he got his Yubikey in one week. So I guess they're pretty interested for devs to program with their device.

Thanks!

**Comment by mhogomchungu** [comment] 2019-05-18 13:00
Will add support for it if i get my hands on one.

How much do they cost?

**Comment by bungabunga** [comment] 2019-05-18 13:15
Different Yubikeys 5 [cost](https://www.yubico.com/store/) from 34$ to 60$ 

If you'd like I could make a customer support ticket for you? (don't worry they won't sekd the key to me, they'll contact you)

**Comment by mhogomchungu** [comment] 2019-05-18 13:50
Will appreciate that.

I am in Tanzania and its somewhere on the middle-eastern side of Africa.

They may need to know this before coming themselves to sending on just in case they dont ship to this side of the world for whatever reason.

**Comment by bungabunga** [comment] 2019-05-18 16:59
ok, let's first try this way:

hi, @yubichris, would you be able to help this developer with a free Yubikey to get it integrated into his software?

[zuluCrypt](https://mhogomchungu.github.io/zuluCrypt/) is a one of a very few front ends to cryptsetup (and TrueCrypt/VeraCrypt also) and it allows easy management of encrypted block devices on linux. I think it is in Yubico's best interest for Yubikeys to get integrated.

Thanks!

**Comment by mhogomchungu** [comment] 2019-05-18 17:17
If i can make it work with zuluCrypt then i will also make it work with SiriKali[1]

[1] https://mhogomchungu.github.io/sirikali/

**Comment by yubichris** [comment] 2019-05-18 19:57
Happy to help! Open a support case at yubi.co/support (select "I need technical support") and let us know what model(s) you need for testing. My team can send you a coupon code to order on Monday. If you provide the 5 digit ticket number I'd be happy to make sure the request is expedited.

**Comment by mhogomchungu** [comment] 2019-05-19 04:22
@bungabunga 

What models should i ask for?

**Comment by bungabunga** [comment] 2019-05-19 04:55
@mhogomchungu 

Yubikey 5 or smaller 5 Nano if you want a USB-A key

or Yubikey 5C / 5C Nano if you want a USB-C one.

The blue ones don't support challenge:response protocol.

https://www.yubico.com/store/

**Comment by mhogomchungu** [comment] 2019-05-19 20:44
I just sent the request and the ticket number is #72472]

**Comment by mhogomchungu** [comment] 2019-05-20 19:39
An update.

I have received an email with a coupon code.

**Comment by bungabunga** [comment] 2019-05-20 21:03
i'm very happy for you. it's a great device, i hope it would serve you well as a developer.

and a special thanks to @yubichris!

**Comment by mhogomchungu** [comment] 2019-05-26 05:10
An update.

Its on its way and it will arrive on Thursday, 30/05/2019.

![Screenshot_20190526_080809](https://user-images.githubusercontent.com/3496115/58377633-ab25ac80-7f8d-11e9-8c25-dae73090ad35.png)

**Comment by mhogomchungu** [comment] 2019-05-28 11:14
An update:

I just received it.

![IMG_20190528_140324](https://user-images.githubusercontent.com/3496115/58474073-e58c7680-8152-11e9-9678-c47837ad7ba2.png)

Thank you guys.

**Comment by yubichris** [comment] 2019-05-28 18:19
very happy to help!

**Comment by mhogomchungu** [comment] 2019-05-28 18:22
The git version can now unlock volumes using yubikey's challence-responce feature.

Where the option is in zuluCrypt-gui is in the attached image below.

By default, zuluCrypt will sends the challenge using ```/full/path/ykchalresp -2 -i -``` command and sends the returned value to zuluCrypt-cli.

There is an option in the config file(~/.config/zuluCrypt/zuluCrypt.conf) to change the slot to send the challenge.

Will appreciate if you can confirm that it works.

![Screenshot_20190528_211703](https://user-images.githubusercontent.com/3496115/58501918-28b80b00-818e-11e9-93ee-0bb7aaee5a0f.png)

**Comment by bungabunga** [comment] 2019-05-31 22:33
unfortunetly I don't have the knowledge to buld an app (any!) from source without detailed instruction.

**Comment by mhogomchungu** [comment] 2019-06-01 06:42
What distribution are you using?

**Comment by bungabunga** [comment] 2019-06-01 06:50
Ubuntu 19.04.

**Comment by mhogomchungu** [comment] 2019-06-01 07:49
0. What package manager do you use to install/uninstall packages?
1. Uninstall all zuluCrypt packages you have installed. There will be a bunch of them so make sure all are gone.
2. Go here[1] and download the following packages: "libzulucrypt1_5.5.0.1559142707.2451082c-0_amd64.deb", "zulucrypt-cli_5.5.0.1559142707.2451082c-0_amd64.deb" and "zulucrypt-gui_5.5.0.1559142707.2451082c-0_amd64.deb".
3. Install them in the order i gave them above. You should be able to install them simply by clicking on each package.

**Comment by bungabunga** [comment] 2019-06-01 09:15
installed. made a test LUKS container. added YC/chal-rsp password. could not open it with zuluCrypt but can open it with yubikey-luks.
"volume could not be opened with the presented key"

tried to get some logs with Show Debug Window opened but there was nothing useful there.

**Comment by mhogomchungu** [comment] 2019-06-01 12:37
You created a test volume with yubikey-luks and zuluCrypt cant open the test volume?

I hit the problem a few times while developing the feature and i discovered the problem and either yubikey-luks missed it or were ok with ykchalresp behavior.

ykchalresp tool adds a new line character at the end of its output probably to make it easier for people who run the tool from the command line and zuluCrypt removes the new line character it thinks its a mistake to pass it on.[1]

yubikey-luks gets a response here[2] and with my limited understanding of bash scripts, i dont see any attempt at removing the new line character and i think the incompatibility between the two tools is here.

I may add a switch to support yubikey-luks behavior but the problem remains of what behavior should be the default.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/2451082c2b24935e7b38c33199f063875cc39967/zuluCrypt-gui/utility.cpp#L2954-L2960

[2] https://github.com/cornelinux/yubikey-luks/blob/5df2b95c30fc963bc76291de487b5654e558baf9/yubikey-luks-open#L53

**Comment by mhogomchungu** [comment] 2019-06-01 13:33
1. Go to the previous link at[1] and redownload and reinstall the 3 packages(libzulucrypt1, zulucrypt-cli and zulucrypt-gui)

2. Go to ```$HOME/.config/zuluCrypt/``` and then add to a config file named ```zuluCrypt.conf``` the following line: ```RemoveYkchalrespNewLineCharacter=true```.

3. Start zuluCrypt and check if it can now unlock the test volume.
[1] https://build.opensuse.org/package/binaries/home:mhogomchungu/zuluCrypt/xUbuntu_19.04

**Comment by mhogomchungu** [comment] 2019-06-01 14:39
I suspect this[1] bug report is primarily caused by ```yubikey-luks``` script passing forward the new line character appended by ```ykchalresp```.

[1] https://github.com/cornelinux/yubikey-luks/issues/10

**Comment by bungabunga** [comment] 2019-06-01 23:00
I tried what you suggested but without luck. the container still doesn't open.

**Comment by bungabunga** [comment] 2019-06-01 23:26
I also installed ykfde and add a yc/chrsp password to the test volume that way. it also doesen't open via zuluCrypt but it opens with ykfde-open command.

**Comment by mhogomchungu** [comment] 2019-06-02 05:32
1. Run ```ykchalresp``` tool manually and give it a challenge and then take its response.
2. Add the response to the test volume.
3. Use zuluCrypt to unlock the test volume and report if it succeeded or not.

These different wrappers to ykchalresp may be doing things differently and we should first establish that zuluCrypt can work with ykchalresp tool.

**Comment by bungabunga** [comment] 2019-06-02 06:47
what do you mean by "2. Add the response to the test volume"?

**Comment by mhogomchungu** [comment] 2019-06-02 08:30
```
[ink@mtz ~]$ ykchalresp -2 xyz
b3d684977f20dadf981418192c8ef5f89160fab8
[ink@mtz ~]$ 
```
In the above example, i sent a challenge "xzy" to slot 2 of yubikey and the yubikey responded with
```b3d684977f20dadf981418192c8ef5f89160fab8``` and this response is the key to add to your LUKS volume because it is the value zuluCrypt uses. 

Test zuluCrypt by comparing it to a direct usage of ykchalresp and by checking if it can unlock volumes created by other tools.

This "ykfde" sends the challenge to ykchalresp and gets the response here[1] but hashes the response here[2] for a reason i can not figure out just by looking at the code. This tool then uses the result of its own hash and not the result returned by ykchalresp.

[1] https://github.com/bpereto/ykfde/blob/4a74a1f483533de6a2ebd5c65d888d1be3995ac3/bin/ykfde.c
[2] https://github.com/bpereto/ykfde/blob/4a74a1f483533de6a2ebd5c65d888d1be3995ac3/bin/ykfde.c#L331

**Comment by bungabunga** [comment] 2019-06-02 09:03
ah, then the problem with yubikey-luks is that I use the hardening as suggested []([here](https://github.com/cornelinux/yubikey-luks).) options CONCATENATE=1 and HASH=1 in /etc/ykluks.cfg
i don't know about the ykfde.

**Comment by mhogomchungu** [comment] 2019-06-06 06:17
Closing this one as "fixed".

Thank for the feature request and many, many more thanks to yubikey for offering a few device to test on.

**Closed by mhogomchungu** 2019-06-06 06:17 UTC
